spawn:
  mode: FREEZE
  world: world
  x: 0.5
  y: 64.0
  z: 0.5

login:
  timeout_seconds: 45
  allow_ip_session: true
  session_minutes: 30
  max_failed_attempts: 5
  lock_minutes: 15

password:
  min_length: 8
  require_digit: true
  require_letter: true

storage:
  driver: SQLITE
  mysql:
    host: 127.0.0.1
    port: 3306
    database: faskin
    user: faskin
    password: "change_me"

whitelist_commands:
  - /register
  - /login

messages_locale: fr
