# Mode d'attente pré-auth
# FREEZE  : le joueur reste où il est, on bloque les mouvements (via events)
# TELEPORT: on téléporte au spawn (cf. spawn.world) et on bloque pareil
spawn:
  mode: FREEZE
  world: world

login:
  timeout_seconds: 45
  # Session IP (TICKET-103)
  allow_ip_session: true
  session_minutes: 30

password:
  min_length: 8
  require_digit: true
  require_letter: true

storage:
  driver: SQLITE # SQLITE | SQLITE_INMEMORY | INMEMORY

# Nouveau: restrictions pré-auth
preauth:
  block:
    movement: true
    chat: true
    commands: true
    interact: true
    inventory_click: true
    item_drop: true
    item_pickup: true
    swap_hand: true
    damage_to_player: true     # annule les dégâts reçus par un joueur non auth
    damage_from_player: true   # annule les dégâts infligés par un joueur non auth
    hunger: true               # empêche la barre de faim de bouger
  commands:
    whitelist:
      - register
      - login
      - tell
      - msg
      - r
      - help

