# Mode d'attente pré-auth
# FREEZE  : le joueur reste où il est, on bloque les mouvements (via events)
# TELEPORT: on téléporte au spawn (cf. spawn.world) et on bloque pareil
spawn:
  mode: FREEZE
  world: world

login:
  timeout_seconds: 45              # kick si non-auth après ce délai
  # Session IP (TICKET-103)
  allow_ip_session: true
  session_minutes: 30
  # Anti-bruteforce
  max_failed_attempts: 5           # après N échecs -> lock
  lock_minutes: 15                 # durée du lock
  min_seconds_between_attempts: 2  # cooldown local par joueur
  kick_on_timeout: true            # true => kick; false => message périodique

password:
  min_length: 8
  require_digit: true
  require_letter: true

storage:
  driver: SQLITE # SQLITE | SQLITE_INMEMORY | INMEMORY

# Nouveau: restrictions pré-auth
preauth:
  block:
    movement: true
    chat: true
    commands: true
    interact: true
    inventory_click: true
    item_drop: true
    item_pickup: true
    swap_hand: true
    damage_to_player: true     # annule les dégâts reçus par un joueur non auth
    damage_from_player: true   # annule les dégâts infligés par un joueur non auth
    hunger: true               # empêche la barre de faim de bouger
  commands:
    whitelist:
      - register
      - login
      - tell
      - msg
      - r
      - help

# i18n
messages_locale: fr        # support existant
messages:
  locale: fr               # nouveau champ supporté en plus de messages_locale
  color_codes: true        # activer les codes '&' -> couleurs
  use_prefix: true         # préfixer tous les messages
# prefix défini dans messages.yml (clé 'prefix')

# Rappels d'auth (actionbar / chat)
reminder:
  enabled: true
  interval_seconds: 15
  actionbar: true
  chat_on_join: false

premium:
  enabled: true
  mode: PROXY_SAFE            # PROXY_SAFE | SPIGOT_FALLBACK (pas de bypass en fallback)
  skip_password: true         # bypass /login si PREMIUM_SAFE
  auto_register: true         # création compte si absent lors d'un PREMIUM_SAFE
  require_ip_forwarding: true # refuse bypass si le proxy ne transmet pas UUID/IP/skins
  metrics: true               # expose métriques internes (log & /faskin stats)
  debug: false                # logs détaillés (à n'activer qu'en test)
# Forwarding modern recommandé : Velocity `player-info-forwarding-mode="modern"`.

