apply:
  update-on-join: true
  refresh-tablist: true
  protocollib-enable: true

cache:
  ttl-seconds: 3600
  max-entries: 500

lookups:
  allow-premium-name: true
  allow-textures-url: true
  allow-unsigned: true

storage:
  type: YAML
  file: "data/skins.yml"
  ttl-seconds: 86400  # 24h

