# HeneriaCore configuration (squelette)
general:
  require-auth: false
premium:
  enable: true
  rate:
    rpm: 120
auth:
  db: "data/heneria.db"
  hash: "pbkdf2"
  salt-length: 16
  session-ttl-seconds: 86400
  autoLoginAfterRegister: true
  maxFailedAttempts: 5
  lockDurationSeconds: 300
  executor-threads: 2
skin:
  apply-on-login: true
