name: HeneriaCore
main: fr.heneriacore.HeneriaCore
version: "0.0.1"
api-version: "1.21"
description: "HeneriaCore - monolithic plugin (premium auth + auth-local + skins). Skeleton init."
authors: ["OpenAI"]
softdepend: []   # ajouter ProtocolLib plus tard en softdepend si nécessaire
