name: HeneriaCore
main: fr.heneriacore.HeneriaCore
version: "0.0.3"
api-version: "1.21"
description: "HeneriaCore - monolithic plugin (premium auth + auth-local + skins). Skeleton init."
authors: ["OpenAI"]
softdepend: []   # ajouter ProtocolLib plus tard en softdepend si nécessaire
commands:
  heneria:
    description: "Authentication commands"
    usage: "/heneria <register|login|logout>"
    permission: heneria.auth
permissions:
  heneria.auth:
    description: "Allow use of auth commands"
    default: true
  heneria.auth.admin:
    description: "Admin auth permissions"
    default: op
