name: Faskin
version: '${project.version}'
main: com.monprojet.faskin.Faskin
api-version: '1.21'
author: ProjetServeur
description: Une solution d'authentification tout-en-un pour les serveurs Spigot.
depend: [ProtocolLib]
