name: skinview
main: com.heneria.skinview.SkinviewPlugin
version: 0.5.2
api-version: "1.21"
author: Heneria
website: https://heneria.example
softdepend: [ProtocolLib]

commands:
  skinview:
    description: Commande principale du plugin skinview
    usage: "/skinview help"
    aliases: [skin, sv]
    permission: skinview.use

permissions:
  skinview.use:
    default: true
    description: Utiliser /skinview (help)
  skinview.admin:
    default: op
    description: Admin (reload + futures opérations sensibles)
