name: HeneriaCore
main: fr.heneriacore.HeneriaCore
version: "0.0.8.1"
api-version: "1.21"
description: "HeneriaCore - core auth/premium/skins"
authors:
  - "Heneria"
softdepend: [ProtocolLib]
commands: {}
permissions: {}
