name: Faskin
main: com.faskin.auth.FaskinPlugin
version: 0.0.2
api-version: '1.21'
authors: [ 'GordoxGit' ]
website: 'https://github.com/GordoxGit/Faskin'
description: 'Auth offline (étape 1), auto-login premium (étape 2), skins premium offline (étape 3).'
commands:
  register:
    description: 'Créer un compte Faskin'
    usage: '/register <password> <confirm>'
    permission: 'faskin.register'
  login:
    description: 'Se connecter à Faskin'
    usage: '/login <password>'
    permission: 'faskin.login'
  logout:
    description: 'Se déconnecter'
    usage: '/logout'
    permission: 'faskin.logout'
  changepassword:
    description: 'Changer le mot de passe'
    usage: '/changepassword <old> <new> <confirm>'
    permission: 'faskin.changepassword'
  faskin:
    description: 'Commande admin Faskin'
    usage: '/faskin reload|status [player]'
    permission: 'faskin.admin'
permissions:
  faskin.register: { default: true }
  faskin.login: { default: true }
  faskin.logout: { default: true }
  faskin.changepassword: { default: true }
  faskin.admin: { default: op }
