name: build
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Clean
        run: gradle clean --no-daemon

      - name: Build (shadow)
        run: gradle build --no-daemon

      - name: Show version
        run: echo "Building Faskin 0.1.0-SNAPSHOT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Faskin-0.1.0-SNAPSHOT.jar
          path: build/libs/*.jar
