name: Java CI (Gradle)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up Gradle
        uses: gradle/setup-gradle@v3
        with:
          gradle-version: '8.14.3'
      - name: Build
        run: gradle clean build --no-daemon
