name: CI (Gradle sans wrapper)

on:
  push: { branches: [ "**" ] }
  pull_request: { branches: [ "**" ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      # Installe et utilise Gradle côté runner (aucun wrapper requis dans le repo)
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2
          arguments: clean check --no-daemon
      - if: ${{ github.event_name == 'pull_request' }}
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2
          arguments: build --no-daemon
