name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (ex: v0.0.10). Si vide, n’exécute pas le tagging."
        required: false
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Install Gradle 9.0.0 (SDKMAN)
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 9.0.0
          gradle --version

      - name: Create tag (manual)
        if: ${{ inputs.tag != '' }}
        run: |
          git tag "${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"

      - name: Clean build
        run: gradle clean --no-daemon

      - name: Build (shadowJar)
        run: gradle build shadowJar --no-daemon

      - name: Compute checksums
        shell: bash
        run: |
          mkdir -p dist
          cp build/libs/Faskin-*.jar dist/
          (cd dist && sha256sum Faskin-*.jar > SHA256SUMS.txt)
          echo "Artifacts:"
          ls -l dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/Faskin-*.jar
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
